### PR TITLE
Creating version 7.5 including latest L10N updates.

### PR DESCRIPTION
**Pull request by abdel792**
#### This PR contains:

1. An update of the __init__.py module including only a new comment for version 7.5;
2. An update of the buildVars.py module including the version update;
3. All the latest L10N updates received from SRT repo.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
This PR is right for me an changes can be merged.
Thanks

**Comment by nvdaes** [comment]
Accidentally closed. Please merge, this is valid for me.

**Comment by abdel792** [comment]
Hi @nvdaes,

Thanks a lot for your approval.

Kind regards.

**Review by nvdaes — COMMENTED** [review]
Hi Abdel, happy to see you again!

1. Should be use GitHub Actions to synchronize translations?
2. I think that the main repo where this is maintained is @zvonimir. In this case, shouldn't PR be done here?
3. I see that the English documentation claims for compatibility until 2021.2. This is not right since the last stable API published is for NVDA 2021.1.

Cheers

**Comment by nvdaes** [comment]
Sorry, this has appeared on my mailbox, not sure why, and I thought that Abdel had updated this.

**Comment by nvdaes** [comment]
Seems that the first message received by me comes from @zstanecic .
My review applies anyway.

**Comment by zstanecic** [comment]
Hi,
I disagree here, as the situation changed.
Let's jump to version 8.0. I've merged the new version to my repo.

**Comment by nvdaes** [comment]
This PR is not being useful now and it's updated every time that changes are commited to master, so I'll close it for now.

@zstanecic, I'll give you write access to this repo so you can merge changes to stable branch for translators, as a maintainer.

**Pull request closed without merging**
